### ISSUE TITLE
Need to set `NODE_OPTIONS=--openssl-legacy-provider` when running `yarn start`

### ISSUE THREAD

**Issue by Torgen** [on3iro/aeons-end-randomizer#537]
**Describe the bug**
App is using an older version of react scripts which is not compatible with current Node versions unless the environment variable is set.

**To Reproduce**
Run `yarn start`

**Expected behavior**
App builds and starts

**Actual Behavior**
```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/mnt/c/Users/Dan/Documents/GitHub/aeons-end-randomizer/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/mnt/c/Users/Dan/Documents/GitHub/aeons-end-randomizer/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/mnt/c/Users/Dan/Documents/GitHub/aeons-end-randomizer/node_modules/webpack/lib/NormalModule.js:471:10)
    at /mnt/c/Users/Dan/Documents/GitHub/aeons-end-randomizer/node_modules/webpack/lib/NormalModule.js:503:5
    at /mnt/c/Users/Dan/Documents/GitHub/aeons-end-randomizer/node_modules/webpack/lib/NormalModule.js:358:12
    at /mnt/c/Users/Dan/Documents/GitHub/aeons-end-randomizer/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/mnt/c/Users/Dan/Documents/GitHub/aeons-end-randomizer/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/mnt/c/Users/Dan/Documents/GitHub/aeons-end-randomizer/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/mnt/c/Users/Dan/Documents/GitHub/aeons-end-randomizer/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/mnt/c/Users/Dan/Documents/GitHub/aeons-end-randomizer/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/mnt/c/Users/Dan/Documents/GitHub/aeons-end-randomizer/node_modules/webpack/lib/NormalModule.js:417:16)
    at /mnt/c/Users/Dan/Documents/GitHub/aeons-end-randomizer/node_modules/webpack/lib/NormalModule.js:452:10
    at /mnt/c/Users/Dan/Documents/GitHub/aeons-end-randomizer/node_modules/webpack/lib/NormalModule.js:323:13
    at /mnt/c/Users/Dan/Documents/GitHub/aeons-end-randomizer/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /mnt/c/Users/Dan/Documents/GitHub/aeons-end-randomizer/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/mnt/c/Users/Dan/Documents/GitHub/aeons-end-randomizer/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /mnt/c/Users/Dan/Documents/GitHub/aeons-end-randomizer/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04 on WSL2
 - Node Version: v18.19.1

**Comment by on3iro** [comment]
Yeah, ideally we would switch to vite #494 and modernize our dependencies. However I currently don't have time to do this.
